<?php
/**
 * Configuration File - Generated by Installer
 * Last Updated: 2026-02-02 (Force Sync)
 */

define('BCB_API_URL', 'https://app.banglachatbot.com/api');
define('BCB_API_KEY', '1-5bKgqnZ1602789813cGYbNDm');

define('BKASH_BASE_URL', 'https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout');
define('BKASH_APP_KEY', 'tSpZnMR4ka2eXdlMvSJayUxPtc');
define('BKASH_APP_SECRET', 'gvblpKPrO8b5SUOMWHxcupc8oJ1TtzS85RUOO2DyOEqOTSfJDOjh');
define('BKASH_USERNAME', '01842999929');
define('BKASH_PASSWORD', '4|)f6Sp)rf');

define('OFFER_PACKAGE_ID', 28);
define('OFFER_PRICE', '999.00');
define('OFFER_CURRENCY', 'BDT');

define('SITE_URL', 'http://offer.banglachatbot.com');
define('CALLBACK_URL', SITE_URL . '/callback.php');

// SMTP Configuration
define('SMTP_HOST', 'email-smtp.ap-southeast-2.amazonaws.com');
define('SMTP_PORT', 587);
define('SMTP_USERNAME', 'AKIAXNKJHE4LUSHHQX75');
define('SMTP_PASSWORD', 'BHmj9TS/inERd7UZstYmtJxfPqXKinc1M6MXRVVsYldc');
define('SMTP_ENCRYPTION', 'tls');
define('SMTP_FROM_EMAIL', 'noreply@banglachatbot.com');
define('SMTP_FROM_NAME', 'Bangla Chatbot');

define('WHATSAPP_SUPPORT', '8801707676797');
?>