<?php
/**
 * Installer for Bangla Chatbot Offer Page
 */

$config_file = 'config.php';

if (isset($_POST['install'])) {
    $bcb_api_key = trim($_POST['bcb_api_key']);
    $bkash_app_key = trim($_POST['bkash_app_key']);
    $bkash_app_secret = trim($_POST['bkash_app_secret']);
    $bkash_username = trim($_POST['bkash_username']);
    $bkash_password = trim($_POST['bkash_password']);
    $bkash_url = trim($_POST['bkash_url']);
    $site_url = rtrim(trim($_POST['site_url']), '/');

    $config_content = "<?php
/**
 * Configuration File - Generated by Installer
 */

define('BCB_API_URL', 'https://app.banglachatbot.com/api');
define('BCB_API_KEY', '$bcb_api_key');

define('BKASH_BASE_URL', '$bkash_url');
define('BKASH_APP_KEY', '$bkash_app_key');
define('BKASH_APP_SECRET', '$bkash_app_secret');
define('BKASH_USERNAME', '$bkash_username');
define('BKASH_PASSWORD', '$bkash_password');

define('OFFER_PACKAGE_ID', 16);
define('OFFER_PRICE', '999.00');
define('OFFER_CURRENCY', 'BDT');

define('SITE_URL', '$site_url');
define('CALLBACK_URL', SITE_URL . '/callback.php');
?>";

    if (file_put_contents($config_file, $config_content)) {
        $success = "কনফিগারেশন ফাইল সফলভাবে তৈরি করা হয়েছে!";
    } else {
        $error = "ফাইলটি তৈরি করতে সমস্যা হয়েছে। দয়া করে ফোল্ডারের রাইট পারমিশন চেক করুন।";
    }
}
?>
<!DOCTYPE html>
<html lang="bn">

<head>
    <meta charset="UTF-8">
    <title>Bangla Chatbot Installer</title>
    <style>
        body {
            font-family: 'Inter', sans-serif;
            background: #0b0e14;
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .wizard {
            background: rgba(255, 255, 255, 0.05);
            padding: 40px;
            border-radius: 20px;
            border: 1px solid rgba(255, 255, 255, 0.1);
            width: 100%;
            max-width: 500px;
        }

        h2 {
            text-align: center;
            color: #8a2be2;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-size: 0.9rem;
            color: #aaa;
        }

        input {
            width: 100%;
            padding: 12px;
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid #333;
            border-radius: 8px;
            color: #fff;
            box-sizing: border-box;
        }

        button {
            width: 100%;
            padding: 15px;
            background: #8a2be2;
            border: none;
            border-radius: 8px;
            color: #fff;
            font-weight: bold;
            cursor: pointer;
        }

        .msg {
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 8px;
            text-align: center;
        }

        .success {
            background: rgba(0, 255, 0, 0.1);
            color: #00ff00;
        }

        .error {
            background: rgba(255, 0, 0, 0.1);
            color: #ff0000;
        }
    </style>
</head>

<body>
    <div class="wizard">
        <h2>Setup Wizard</h2>
        <?php if (isset($success))
            echo "<div class='msg success'>$success <br><a href='index.php' style='color: #fff;'>Landing Page দেখুন</a></div>"; ?>
        <?php if (isset($error))
            echo "<div class='msg error'>$error</div>"; ?>

        <form method="POST">
            <div class="form-group">
                <label>Site URL (e.g. http://offer.banglachatbot.com)</label>
                <input type="text" name="site_url" required placeholder="http://domain.com">
            </div>
            <div class="form-group">
                <label>BCB API Key</label>
                <input type="text" name="bcb_api_key" required>
            </div>
            <div class="form-group">
                <label>bKash App Key</label>
                <input type="text" name="bkash_app_key" required>
            </div>
            <div class="form-group">
                <label>bKash App Secret</label>
                <input type="text" name="bkash_app_secret" required>
            </div>
            <div class="form-group">
                <label>bKash Username</label>
                <input type="text" name="bkash_username" required>
            </div>
            <div class="form-group">
                <label>bKash Password</label>
                <input type="password" name="bkash_password" required>
            </div>
            <div class="form-group">
                <label>bKash Base URL</label>
                <input type="text" name="bkash_url" value="https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout"
                    required>
                <small style="font-size: 0.7rem; color: #888;">Live:
                    https://tokenized.pay.bka.sh/v1.2.0-beta/tokenized/checkout</small>
            </div>
            <button type="submit" name="install">ইন্সটল করুন</button>
        </form>
    </div>
</body>

</html>